export const START_PROCESSING = 'START_PROCESSING';
export const CANCEL_PROCESSING = 'CANCEL_PROCESSING';
export const PROCESSING_FINISHED = 'PROCESSING_FINISHED';
export const PROCESSING_PROGRESS = 'PROCESSING_PROGRESS';

export const PROCESSING_OPERATION_INFO = 'PROCESSING_OPERATION_INFO';
export const PROCESSING_OPERATION_RESULT = 'PROCESSING_OPERATION_RESULT';
